// Extended LNS Research Document
// Based on: AI Accelerator for a Core RISC-V (Teixeira & Paradela)
// Extended to cover lns8, lns16, lns32, lns64 and new approximation methods

#set document(
  title: "Logarithmic Number System: Approximation Methods and Extended Precision Formats",
  author: ("Henrique Teixeira"),
)

#set page(
  paper: "a4",
  margin: (left: 25mm, right: 25mm, top: 25mm, bottom: 25mm),
  header: context {
    if counter(page).get().first() > 1 [
      #set text(size: 9pt, style: "italic")
      #align(right)[LNS: Approximation Methods and Extended Precision Formats]
      #line(length: 100%, stroke: 0.4pt)
    ]
  },
  footer: context {
    if counter(page).get().first() > 1 [
      #line(length: 100%, stroke: 0.4pt)
      #set text(size: 9pt)
      #align(right)[#counter(page).display("1 / 1", both: true)]
    ]
  },
)

#set text(
  font: "New Computer Modern",
  size: 11pt,
  lang: "en",
)

#set par(
  justify: true,
  leading: 0.65em,
  spacing: 1em,
)

#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  v(1em)
  text(size: 18pt, weight: "bold")[#it]
  v(0.5em)
}

#show heading.where(level: 2): it => {
  v(1em)
  text(size: 14pt, weight: "bold")[#it]
  v(0.5em)
}

#show heading.where(level: 3): it => {
  v(0.75em)
  text(size: 12pt, weight: "bold")[#it]
  v(0.25em)
}

#show link: set text(fill: rgb("#8c2d19"))
#set math.equation(numbering: "(1)")
#show figure.caption: set text(size: 10pt)

#let projtitle = "LNS: Approximation Methods and Extended Precision Formats"
#let projauthor = "Henrique Teixeira"
#let supervisor = "Nuno Paulino"

// Cover page
#align(center + horizon)[
  #v(0.25fr)
  #text(size: 28pt, weight: "bold")[#projtitle]
  #v(8mm)
  #text(size: 14pt, weight: "bold")[#projauthor]
  #v(10mm)
  #datetime.today().display()
  #v(1fr)
]

#pagebreak()

// Abstract
#heading(numbering: none, outlined: false)[Abstract]

This document extends previous work on the Logarithmic Number System (LNS) arithmetic unit for RISC-V, which demonstrated a 16-bit LNS format achieving IEEE-754 equivalent precision for neural network weights using linear spline approximation with a greedy algorithm, requiring only 324 bytes of memory and synthesizing at 125 MHz on FPGA.

The present work broadens this foundation in two directions. First, it revisits lns8 Q4.3 and lns16 Q8.7 with a systematic comparison of approximation methods beyond linear splines, including Newton's divided differences, minimax polynomial approximation via the Remez algorithm, and piecewise Chebyshev approximation. Second, it extends the LNS framework to lns32 Q16.15 and lns64 Q32.31, where the domain of the correction functions $f^+(x) = log_2(1 + 2^x)$ and $f^-(x) = log_2(1 - 2^x)$ grows significantly and spline table sizes become impractical, motivating the transition to compact polynomial approximations.

#pagebreak()

// Acknowledgements
#heading(numbering: none, outlined: false)[Acknowledgements]

We would like to thank our supervisor Nuno Paulino and co-supervisors Luís Sousa and Guilherme Oliveira for the help and guidance during this work.

#pagebreak()

#outline(
  title: "Table of Contents",
  indent: auto,
)

#pagebreak()

#outline(
  title: "List of Figures",
  target: figure.where(kind: image),
)

#pagebreak()

#outline(
  title: "List of Tables",
  target: figure.where(kind: table),
)

#pagebreak()

#heading(numbering: none, outlined: false)[List of Acronyms]

#table(
  columns: (auto, 1fr),
  stroke: none,
  align: (left, left),
  [NN],    [Neural Network],
  [FP],    [Floating Point],
  [LNS],   [Logarithmic Number System],
  [LNSU],  [Logarithmic Number System Unit],
  [LUT],   [Look Up Table],
  [DSP],   [Digital Signal Processing block/unit],
  [XF],    [Spline format storing (x, f) point pairs],
  [XMB],   [Spline format storing (x, m, b) segment coefficients],
  [NDD],   [Newton's Divided Differences],
  [MAE],   [Maximum Absolute Error],
  [MRE],   [Maximum Relative Error],
  [RMSE],  [Root Mean Square Error],
)

#pagebreak()

#counter(page).update(1)
#set heading(numbering: "1.1")

= Introduction

The Logarithmic Number System (LNS) offers a compelling alternative to IEEE-754 floating point.
By encoding values as fixed-point binary logarithms, multiplication and division reduce to integer addition and subtraction,
and square root reduces to a single arithmetic right shift. These properties eliminate the need for 
mantissa multipliers in hardware, significantly reducing area and power consumption.

Previous work demonstrated an lns16 Q8.7 arithmetic unit embedded in a RISC-V core,
achieving a maximum one-bit approximation error for addition and subtraction using linear
splines generated by a greedy algorithm, with a total memory footprint of 324 bytes.
The design synthesized at 125 MHz on a Pynq Z2 FPGA with single-cycle latency.

This document builds on that foundation. The first goal is to evaluate alternative approximation
methods for the correction functions required by LNS addition and subtraction on lns8 and lns16 formats,
characterising the trade-off between approximation accuracy, evaluation cost, and memory footprint.
The second goal is to extend the LNS framework to 32-bit and 64-bit formats,
where the growing domain of the correction functions makes the linear spline approach impractical
and more compact polynomial representations become necessary.

== Scope

This document covers:

- A review of the LNS format and the derivation of the correction functions for add and sub operations.
- A summary of the previous linear spline (XF and XMB) approach and its results for lns8 and lns16.
- An analysis of the correction functions' behaviour at increased precision and wider domains (lns32, lns64).
- A survey and analysis of candidate approximation methods: Newton's divided differences,
  minimax polynomial approximation and piecewise Chebyshev approximation.
- A comparison framework for evaluating approximation methods across all four formats.
- Open questions and planned implementation work.

= Background

== The Logarithmic Number System

In LNS, a non-zero real number $x$ is represented by a sign bit $S_x$ and a fixed-point binary logarithm $L_x$:

$
S_x &= cases(
  1\, "if" x < 0,
  0\, "if" x >= 0
) \
L_x &= log_2(|x|) \
x &= (-1)^(S_x) dot.c 2^(L_x)
$

$L_x$ is a two's complement fixed-point number. Negative values of $L_x$ represent magnitudes in $(0, 1)$ and positive values represent magnitudes in $(1, +infinity)$.

== Supported Formats

The previous supported LNS formats use one sign bit and a fixed-point exponent split into integer and fractional parts:

#figure(
  table(
    columns: 5,
    align: center,
    [Format], [$S_x$], [Integer bits], [Fractional bits], [Value range],
    [lns8  Q4.3],  [1], [4], [3],  [$2^(-8)$ to $2^(7.875)$],
    [lns16 Q8.7],  [1], [8], [7],  [$2^(-128)$ to $2^(127.992)$]
  ),
  caption: [LNS format specifications],
) <tab:formats>

The fractional resolution per step is $2^(-F)$ where $F$ is the number of fractional bits, giving a relative quatization error of $2 ^ (2 ^ (-F)) - 1$.
For lns8 this is $2^(-3) = 0.125$, with a relative quantization error per step of approximately $2^(1/8) - 1 approx 9%$.
For lns16 it is $2^(-7) = 0.0078$, approximately $2^(1/128) - 1 approx 0.54%$.

== Arithmetic Operations

The operations in LNS follow directly from the logarithmic representation:

$
z = x dot.c y &<=> L_z = L_x + L_y \
z = x / y &<=> L_z = L_x - L_y \
z = sqrt(x) &<=> L_z = L_x >> 1 \
z = x + y &<=> L_z = L_x + log_2(1 + 2^(L_y - L_x)), quad |x| >= |y| \
z = x - y &<=> L_z = L_x + log_2(1 - 2^(L_y - L_x)), quad |x| >= |y|
$

Multiplication, division, and square root are exact up to quantization.
Addition and subtraction require evaluating the correction functions:

$
f^+(x) &= log_2(1 + 2^x), quad x in (-infinity, 0] \
f^-(x) &= log_2(1 - 2^x), quad x in (-infinity, 0)
$

where $x = L_y - L_x <= 0$ is enforced by swapping operands if necessary so that the larger magnitude is always taken as the base.

\

This comes from the following derivation:

- Given $|x| > |y|$:
$
z &= x plus.minus y \
L_z &= log_2(2 ^ (L_x) plus.minus 2 ^ (L_y)) \
L_z &= log_2(2 ^ (L_x) (1 plus.minus 2 ^ (L_y - L_x))) \
L_z &= L_x + log_2(1 plus.minus 2 ^ (L_y - L_x))
$

== Properties of the Correction Functions

=== Addition: $f^+(x) = log_2(1 + 2^x)$

$f^+$ is smooth and bounded on $(-infinity, 0]$. It increases monotonically from $0$ at $-infinity$ to $1$ at $x = 0$.
Its first and second derivative are:

$
(f^+)'(x)  = (2^x)/(1 + 2^x) \
(f^+)''(x) = ln(2) (2^x)/((1 + 2^x)^2)
$

Both are always positive, monotonically increasing, and approach $0$ at $-infinity$ and $1/2$ and $ln(2)/4$ at $x = 0$, respectively.
These derivatives will be important to derive upper bound expressions for the error functions.

=== Subtraction: $f^-(x) = log_2(1 - 2^x)$

$f^-$ is defined on $(-infinity, 0)$ only. As $x -> 0^-$, $f^-(x) -> -infinity$ due to the singularity of $log_2$ at zero.
Its first and second derivative are:

$
(f^-)'(x) = - (2^x)/(1 - 2^x) \
(f^-)''(x) = - ln(2) (2^x)/((1 - 2^x)^2)
$

These are always negative and diverge to $-infinity$ as $x -> 0^-$.
The unbounded second derivative near $x = 0$ is the fundamental reason that the subtraction function
requires significantly more intervals than the addition function to achieve the same approximation error.
Any approximation method must handle this singularity explicitly,
either by excluding a neighbourhood of $0$ and clamping, or by using a change of variable that regularises the behaviour.

= Previous Work: Linear Splines

== XF and XMB Representations

The previous work approximated $f^+$ and $f^-$ with piecewise linear splines generated by a greedy algorithm.
Given a budget of $n+1$ points $\{(x_i, f_i)\}_{i=0}^{n}$,
the standard linear spline interpolation formula for an interval $[x_(i-1),x_i]$ is:

$ "LS"_i (x) = ((x_i - x) f_(i-1) + (x - x_(i-1)) f_i) / h_i, quad h_i = x_i - x_(i-1) $ <eq:xf>

This is the XF representation. It stores $(x_i, f_i)$ pairs and evaluates the weighted average at query time. An equivalent form is:

$ "LS"_i (x) = m_i dot.c x + b_i, quad m_i = (f_i - f_(i-1))/h_i, quad b_i = (f_(i-1) x_i - f_i x_(i-1))/h_i $ <eq:xmb>

The error upper bound formula for a linear spline is:

$
epsilon <= 1/8 max_[a,b] |f''(x)| h_i^2
$

This is the XMB representation. It precomputes the slope $m_i$ and intercept $b_i$ per segment, reducing runtime evaluation to a single multiply-add. The trade-off is increased memory: XF requires $4(n+1)$ bytes for lns16 (two 2-byte fields per point), while XMB requires $6(n+1)$ bytes (three 2-byte fields).

== Greedy Algorithm

The greedy algorithm starts with the two boundary points and iteratively adds the midpoint of the interval with the largest error estimate:

$
epsilon_i <= (ln(2) dot.c 2^(x_i) dot.c h_i^2) / (8(1 plus.minus 2^(x_i))^2)
$

Since the error bound is monotonically increasing for both functions (the maximum of $|f''|$ on each interval is at the right endpoint), the interval to split is always the one with the largest $h_i$ weighted by the local curvature. The minimum allowed interval length is 2 (in fixed-point units), enforcing that consecutive spline points are distinct in the integer representation.

== Results for lns8 and lns16

#figure(
  table(
    columns: 5,
    align: center,
    table.cell(rowspan: 1)[Format], table.cell(rowspan: 1)[Method], [Operation], [Error (bits)], [Table size (bytes)],
    table.cell(rowspan: 6, align: horizon)[lns8 Q4.3],
    table.cell(rowspan: 3, align: horizon)[XF],
    [Add],     [1], [16],
    [Sub],     [1], [48],
    [Add+Sub], [1], [64],
    table.cell(rowspan: 3, align: horizon)[XMB],
    [Add],     [1], [24],
    [Sub],     [1], [42],
    [Add+Sub], [1], [66],
    table.cell(rowspan: 6, align: horizon)[lns16 Q8.7],
    table.cell(rowspan: 3, align: horizon)[XF],
    [Add],     [1], [40],
    [Sub],     [1], [200],
    [Add+Sub], [1], [240],
    table.cell(rowspan: 3, align: horizon)[XMB],
    [Add],     [1], [72],
    [Sub],     [1], [252],
    [Add+Sub], [1], [324],
  ),
  caption: [Linear spline results for lns8 Q4.3 and lns16 Q8.7],
) <tab:spline_results>

The XF tables achieve lower memory for the same error,
while XMB reduces runtime to a single multiply-add plus a table lookup,
enabling single-cycle latency.

The subtraction table requires substantially more rows than the addition table,
because the second derivative of $f^-$ diverges near $x = 0$,
requiring dense sampling near the singularity.

=== $f^+$ and $f^-$ domain ranges

For an LNS type with precision $p$, the minimum value in absolute terms is $2^(-p)$.
So, we want to find $x < 0$, such that $plus.minus 2^(-p) = log_2(1 plus.minus 2^x)$: 

#math.equation(numbering: none, block: true)[
$
plus.minus 2^(-p) &= log_2(1 plus.minus 2^x) \
2^(plus.minus 2^(-p)) &= 1 plus.minus 2^x \
2^(plus.minus 2^(-p)) - 1 &= plus.minus 2^x \
plus.minus (2^(plus.minus 2^(-p)) - 1) &= 2^x \
x &= log_2(plus.minus (2^(plus.minus 2^(-p)) - 1))
$
]

#figure(
  table(
    columns: 4,
    align: center,
    [Type], [Precision $p$ (bits)], [$x_"min"^+$], [$x_"min"^-$],
    [LNS8 Q4.3],    [3],  [$-3.466$],  [$-3.591$],
    [LNS16 Q8.7],   [7],  [$-7.525$],  [$-7.533$],
    [LNS32 Q16.15], [15], [$-15.529$], [$-15.529$],
    [LNS32 Q8.23],  [23], [$-23.529$], [$-23.529$],
    [LNS64 Q33.30], [30], [$-30.529$], [$-30.529$],
    [LNS64 Q23.40], [40], [$-40.529$], [$-40.529$],
    [LNS64 Q11.52], [52], [$-52.000$], [$-53.000$],
  ),
  caption: [Effective domain lower bound $x_"min"^plus.minus = log_2(2^(plus.minus 2^(-p)) - 1)$ by format and precision],
)

=== FP to LNS and LNS to FP convertion functions 


#math.equation(numbering: none, block: true)[
$
x_(f p) = (-1)^(S_x) dot (1 + m_x) dot 2^(e_x) \
x_(l n s) = (-1)^(S_x) dot 2^(L_x) \
\
x_(f p) = x_(l n s) \
(-1)^(S_x) dot (1 + m_x) dot 2^(e_x) = (-1)^(S_x) dot 2^(L_x) \
(1 + m_x) dot 2^(e_x) = 2^(L_x) \
log_2(1 + m_x) + e_x = L_x \
$
]

\

$
L_x &= e_x + log_2(1 + m_x) \
"float2lns"(m_x) &:= log_2(1 + m_x) \
"lns2float"("lns_f"_x) &:= 2^("lns_f"_x) - 1 \
$

\

#math.equation(numbering: none, block: true)[
$
dif^2/(dif x^2) "float2lns(x)" &= dif/(dif x)(1/ln(2) 1/(1 + x)) \
&= -1/ln(2) 1/(1 + x)^2 \


dif^2/(dif x^2) "lns2float"(x) &:= ln(2)^2 2^x \
$
]

\

$
epsilon_("float2lns") &<= 1/8 1/ln(2) 1/(1 + x_(i - 1))^2 h_i^2 \
epsilon_("lns2float") &<= 1/8 ln(2)^2 2^(x_i) h_i^2 \
$

#pagebreak()

== Limitations at Higher Precision

The linear spline approach works well for lns8 and lns16,
because the domain of the correction functions is small $-$
the argument $x = L_y - L_x$ ranges over at most 8 or 16 bits, respectively.
For lns32 and lns64, the domain grows proportionally with the exponent width,
and the number of intervals required to maintain a fixed error bound scales roughly
as $O(sqrt(1/epsilon)) = O(sqrt(1/(2^(-n)))) = O(2^(n/2))$ per unit of domain,
making table-based approaches impractical.

Additionally, even for lns8 and lns16 there is room to improve approximation quality beyond piecewise linear.
Higher-degree polynomial approximations can achieve the same error with fewer segments or lower error with the
same number of segments.

= Candidate Approximation Methods

This chapter surveys the methods under consideration for replacing or supplementing linear splines for lns8,
lns16, and for use in lns32 and lns64.

== Error Formula

#block(
  stroke: 0.5pt,
  inset: 10pt,
  radius: 4pt,
)[
  *Theorem 1* Lagrange Interpolation Error Formula

  Given a function $f(x) in C^(n+1)[a,b]$, let $p_n (x) in bb(P)_n$ be the interpolative 
  polynomial of $f(x)$ in the unique $x$'s ${x_i | 0 <= i <= n}$, then $forall x in [a,b],
  exists c_x in [a,b]:$

  $
    epsilon = f(x) - p_n (x) = 1 / (n+1)! f^((n+1))(c_x) pi_(n+1)(x)
  $

  where $pi_(n+1)(x) = product_(k=0)^n (x - x_k)$
]


=== $f^+$ and $f^-$ Error Upper Bound

Given $x < 0$:

#math.equation(numbering: none, block: true)[
$
log_2(1 plus.minus 2^x) &= 1/ln(2) ln(1 plus.minus 2^x) \
&= 1/ln(2) integral_(-infinity)^x dif/(dif t) \(ln(1 plus.minus 2^t)\) dif t \
&= 1/ln(2) integral_(-infinity)^x 1/(1 plus.minus 2^t) dif/(dif t)(1 plus.minus 2^t) dif t \
&= plus.minus/ln(2) integral_(-infinity)^x (2^t)/(1 plus.minus 2^t) dif t \
$
]

As $plus.minus 2^t < 0, forall t in (-infinity, x], x < 0$, then $1/(1 plus.minus 2^t)$ can be expanded using the geometric series \
infinite series representation $1 / (1 - r) = sum_(i>=0) r^n$.

#math.equation(numbering: none, block: true)[
$
&= plus.minus/ln(2) integral_(-infinity)^x 2^t sum_(n>=0) (minus.plus 2^(t))^n dif t \
$
]

Since the series converges, the swap of the integration and sumation operations are justified.

#math.equation(numbering: none, block: true)[
$
&= plus.minus/ln(2) sum_(n>=0) (minus.plus 1)^n integral_(-infinity)^x 2^((n + 1) t) dif t \
&= 1/ln(2) sum_(n>=0) (minus.plus 1)^(n-1) lr((1/(ln(2)(n+1)) 2^((n+1) t)) bar.v)_(t->-infinity)^(t=x) \
&= 1/ln(2)^2 sum_(n>=0) (minus.plus 1)^(n-1)/(n+1) 2^((n+1) x) \
&= 1/ln(2)^2 sum_(n>=1) (minus.plus 1)^n/n 2^(n x) \
$
]

And so, we finally get an infinite series representation of $f^+$ and $f^-$.

$
log_2(1 plus.minus 2^x) = 1/ln(2)^2 sum_(n>=1) (minus.plus 1)^n/n 2^(n x), x < 0
$

Now, we can use this infinite series representation to calculate an upper bound for the k-th derivative of both functions:

#math.equation(numbering: none, block: true)[
$
dif^k/(dif x^k) log_2(1 plus.minus 2^x) &= 1/ln(2)^2 dif^k/(dif x^k) sum_(n>=1) (minus.plus 1)^n/n 2^(n x) \
$
]

The switch of the summation and derivative operators is also justified as the series does converge.

#math.equation(numbering: none, block: true)[
$
dif^k/(dif x^k) log_2(1 plus.minus 2^x) &= 1/ln(2)^2 sum_(n>=1) (minus.plus 1)^n/n dif^k/(dif x^k) 2^(n x) \
dif^k/(dif x^k) log_2(1 plus.minus 2^x) &= ln(2)^(k-2) sum_(n>=1) (minus.plus 1)^n n^(k-1) 2^(n x) \
$
]

If we can find a term $a$, such that all terms $n^(k-1) 2^(n x) <= a^n$, then the sum of the terms will be larger than our current series and we have a simple upper bound we can compute.

Following the Alternative Series Estimation Error for $f^+$, \
as $|a_(n+1)| < |a_n| and lim_(n->infinity) a_n = 0, a_n = (minus 1)^n n^(k-1) 2^(n x)$:

#math.equation(numbering: none, block: true)[
$
|a_(n+1)| &< |a_n| \
|(n+1)^(k-1) 2^((n+1)x)| &< |n^(k-1) 2^(n x)| \
(1 + 1/n)^(k-1) &< 2^(-x) \
1 + 1/n &< 2^(-x/(k-1)) \
1/n &< 2^(-x/(k-1)) - 1 \
n &> 1/(2^(-x/(k-1)) - 1) \
$
]

#math.equation(numbering: none, block: true)[
$
|R_n| &< |a_(n+1)| \
\
lr(|sum_(n>=ceil(1/(2^(-x/(k-1)) - 1))) (minus 1)^n n^(k-1) 2^(n x)|) &< lr(|(ceil(1/(2^(-x/(k-1)) - 1))+1)^(k-1) 2^((1+1) x)|) \
&= (ceil(1/(2^(-x/(k-1)) - 1)) + 1)^(k-1) 2^(2x) \
&= (ceil(2^(x/(k-1))/(1 - 2^(x/(k-1)))) + 1)^(k-1) 2^(2x) \
$

$
ceil(2^t/(1-2^t)) + 1
&<= 2^t/(1-2^t) + 2 \
&= (2^t + 2 - 2 dot 2^t)/(1-2^t) \
&= (2 - 2^t)/(1-2^t) \
&= 2(1 - 2^(t-1))/(1-2^t) \
$

$
x < 0 &-> x/(k-1) < 0 -> t < 0\
2(1 - 2^(t-1))/(1-2^t) &<= 1/(1-2^t)\
$

$
(1/(1 - 2^(x/(k-1))))^(k - 1) &= sum_(n >= 0) 2^(x/(k-1))
$

\

$
K &= lr(|sum_(n>=1)^(n = ceil(1/(1 - 2^(x/(k-1))) - 1) - 1) (-1)^n n^(k-1) 2^(n x)|)
$
]

/*
#pagebreak()

By the Abel-Plana formula:
#math.equation(numbering: none, block: true)[
$
sum_(n>=0) (-1)^n f(n) &= 1/2 f(0) + integral_(0)^(infinity) (f(i t) - f(-i t))/(2i sinh(pi t)) dif t \
0 dot 2^0 + sum_(n>=1) (minus 1)^n n^(k-1) 2^(n x) &= 0 + integral_(0)^(infinity) ((i t)^(k-1) 2^(i t x) - (-i t)^(k-1) 2^(-i t x))/(2i sinh(pi t)) dif t, k > 0\
&= - i^(k) integral_(0)^(infinity) t^(k-1) (e^(ln(2) i t x) - (- 1)^(k-1) e^(-ln(2) i t x))/(2 sinh(pi t)) dif t \
&= lr(-i^k (integral_(0)^(infinity) t^(k-1) (cos(ln(2) x t))/sinh(pi t) dif t or integral_(0)^(infinity) t^(k-1) (sin(ln(2) x t))/sinh(pi t) dif t)) \

\
integral_(0)^(infinity) t^(k-1) (cos(a t))/sinh(pi t) dif t &= integral_(0)^(infinity) t^(k-1) cos(a t)/(e^(pi t) - e^(-pi t)) dif t \
&= integral_(0)^(infinity) t^(k-1) e^(-pi t) cos(a t)/(1 - e^(-2pi t)) dif t \
&= integral_(0)^(infinity) t^(k-1) e^(-pi t) cos(a t) sum_(n >= 0) e^(-2pi n t) dif t \
&= sum_(n >= 0) integral_(0)^(infinity) t^(k-1) Re(e^(i a t)) e^(-(2 n + 1) pi t) dif t \
&= Re(sum_(n >= 0) integral_(0)^(infinity) t^(k-1) e^((-pi(2 n + 1) + i a) t) dif t) \
&= Re(sum_(n >= 0) 1/(pi (2n + 1) - i a)^k integral_(0)^(infinity) z^(k-1) e^(-z) dif z) \
&= Gamma(k) Re(sum_(n >= 0) 1/((n + 1/2 - (i a)/(2 pi)) 2 pi)^k) \
&= Gamma(k)/(2pi)^k Re(sum_(n >= 0) 1/(n + 1/2 - (i a)/(2 pi))^k) \
&= Gamma(k)/(2pi)^k Re(sum_(n >= 0) 1/(n + 1/(2pi) - i a/(2 pi))^k) \
&= Gamma(k)/(2pi)^k Re(zeta(k, 1/2 - (i a)/(2pi))) \

\
integral_(0)^(infinity) t^(k-1) (sin(a t))/sinh(pi t) dif t &= Gamma(k)/(2pi)^k Im(zeta(k, 1/2 - i a/(2pi))) \
\

sum_(n>=1) (-1)^n n^(k-1) 2^(n x) &= cases(
  display(-i^k Gamma(k)/(2(2pi)^k) Im(zeta(k, 1/2 - i ln(2)/2 x))) & "if" k "odd",
  display(-i^k Gamma(k)/(2 (2pi)^k) Re(zeta(k, 1/(2pi) - i (ln(2) x)/(2pi)))) & "otherwise"
)
$
]

As $zeta(s, z)$ satisfies the following property $zeta(s, overline(z)) = overline(zeta(s, z))$:

#math.equation(numbering: none, block: true)[
$
sum_(n>=1) (-1)^n n^(k-1) 2^(n x) &= cases(
  display(-(-1)^((k-1)/2) Gamma(k)/(2(2pi)^k) dot i dot Im(zeta(k, 1/(2 pi) - i ln(2)/(2 pi) x))) & "if" k "odd",
  display(-(-1)^(k/2) Gamma(k)/(2(2pi)^k) Re(zeta(k, 1/(2 pi) - i ln(2)/(2 pi) x))) & "otherwise"
)
$
]

#math.equation(numbering: none, block: true)[
$
lr(|sum_(n=0) (-1)^n n^(k-1) 2^(n x)|) &<= lr(|integral_(0)^(infinity) t^(k-1) 1/sinh(pi t) dif t|) \
&<= lr(|integral_(0)^(infinity) t^(k-1) 2/(e^(pi t) - e^(-pi t)) dif t|) \
&<= 2 lr(|integral_(0)^(infinity) t^(k-1) e^(-pi t)/(1 - e^(-2pi t)) dif t|) \
&<= 2 lr(|integral_(0)^(infinity) t^(k-1) e^(-pi t) sum_(m >= 0) e^(-2pi m t) dif t|) \
&<= 2 lr(|integral_(0)^(infinity) sum_(m >= 0) t^(k-1) e^(- (2m + 1) pi t) dif t|) \
&<= 2 lr(|sum_(m >= 0) integral_(0)^(infinity) t^(k-1) e^(- (2m + 1) pi t) dif t|) \
&<= 2 lr(|sum_(m >= 0) integral_(0)^(infinity) (z / ((2m + 1) pi))^(k-1) e^(- z) (dif z)/((2m + 1) pi)|) \
&<= 2 lr(|sum_(m >= 0) 1 / ((2m + 1) pi)^k integral_(0)^(infinity) z^(k-1) e^(- z) dif z|) \
&<= 2 lr(|Gamma(k)/pi^k (sum_(m >= 1) 1 / m^k - sum_(m >= 1) 1 / (2m)^k)|) \
&<= 2 lr(|Gamma(k)/pi^k (zeta(k) - 2^(-k) sum_(m >= 1) 1 / m^k)|) \
&<= 2 Gamma(k) pi^(-k) zeta(k) (1 - 2^(-k)) \
$
]
*/

Therefore, the k-th derivative of the $f^+$ is bounded by:
#math.equation(numbering: none, block: true)[
$
dif^k/(dif x^k) log_2(1 plus 2^x) &<= ln(2)^(k-2) (K + (1 - 2^(x/(k-1)))^(1-k) 2^(2x)) \
$
]

#pagebreak()

Following D'Alambert Criteria for $f^-$, as $lim_(n->infinity) a_(n+1)/a_n = L, a_n = 2^(n x)/n^(k+1)$:


#math.equation(numbering: none, block: true)[
$
lim_(n->infinity) ((n+1)^(k-1) 2^((n+1) x)) / (n^(k-1) 2^(n x))
&= lim_(n->infinity) 2^((n+1) x - n x) ((n + 1)/n)^(k+1) \
&= 2^x lim_(n->infinity) (1 + 1/n)^(k+1) \
&= 2^x \
\
L < 1 &<=> 2^x < 1\
&<=> x < 0 \
R_n &<= a_(n+1) 1/(1 - L) \
sum_(n>=1) 2^(n x)/n^(k+1) &<= 2^(k-1) 2^(2x) 1/(1 - 2^x) \
&= 2^(2x + k - 1)/(1 - 2^x) \
$
]

Therefore, the k-th derivative of the $f^-$ is bounded by:
#math.equation(numbering: none, block: true)[
$
dif^k/(dif x^k) log_2(1 minus 2^x) &<= ln(2)^(k-2) 2^(2x + k - 1)/(1 - 2^x) <= ln(2)^(k-2) (K + (1 - 2^(x/(k-1)))^(1-k) 2^(2x)) \

2^(2x + k - 1)/(1 - 2^x) &<= (1 - 2^(x/(k-1)))^(1 - k) 2^(2x) \
&<=> 2/(1 - 2^x) <= 1/(1 - 2^(x/(k-1))) \
&<=> 2 - 2 dot 2^(x/(k - 1)) <= 1 - 2^x \
&<=> 2 dot 2^(x/(k-1)) - 2^x >= 1 \
&<=> 2^x (2^(x (1/(k-1) - 1)) - 1) >= 2^(-1) \
$
]

Now we can use the Lagrange Interpolation Error Formula with $n + 1$ points.

#math.equation(numbering: none, block: true)[
$
epsilon^+ <= max_(x in [a,b]) 1/(n+1)! ln(2)^((n+1)-2) (K + (1-2^(x/((n+1) - 1)))^(1-(n+1)) 2^(2x)) lr(|pi_(n+1) (x)|) \
epsilon^- <= max_(x in [a,b]) 1/(n+1)! ln(2)^((n+1)-2) 2^(2x + (n + 1) - 1)/(1 - 2^x) lr(|pi_(n+1) (x)|) \
$
]

For an interval $[a,b]$, ${x_i | 0 <= i <= n} in [a,b]$, where $n$ is the degree of the polynomial
on the interval $[a,b]$ and $x in [a,b]$ and $x < 0$:

#math.equation(numbering: none, block: true)[
$
epsilon^+_n <= max_(x in [a,b]) 1/(n+1)! ln(2)^(n-1) (K + (1-2^(x/n))^(-n) 2^(2x)) (b-a)^(n+1) \
epsilon^-_n <= max_(x in [a,b]) 1/(n+1)! ln(2)^(n-1) 2^(2x + n)/(1 - 2^x) (b-a)^(n+1) \

epsilon^+_n <= 1/(n+1)! ln(2)^(n-1) (K + (1-2^(x/n))^(-n) 2^(2x)) (b-a)^(n+1) \
epsilon^-_n <= 1/(n+1)! ln(2)^(n-1) 2^(2b + n)/(1 - 2^b) (b-a)^(n+1) \
$
]

Splitting the functions into multiple branches with intervals
${[x_(i-1), x_i] | 0 <= i <= k}$ with degree $n_i$:

$
epsilon^+_(n_i) <= 1/(n_i+1)! ln(2)^(n_i-1) (K + (1-2^(x/n_i))^(-n_i) 2^(2x)) h_i^(n_i+1) \
epsilon^-_(n_i) <= 1/(n_i+1)! ln(2)^(n_i-1) 2^(2x_i + n_i)/(1 - 2^(x_i)) h_i^(n_i+1) \
$

Now, we have an upper bound that we can use to modulate the approximation error
of both functions in all $k$ sections.

But we can go further. Let $p$ be the precision of our LNS format, that is, LNS$n$-Q$i$.$p$,
we want $epsilon_(n_i) <= 2^(-p)$:

#math.equation(numbering: none, block: true)[
$
2^(-p^+) <= 1/(n_i+1)! ln(2)^(n_i-1) h_i^(n_i+1) (K + (1-2^(x/n))^(-n_i) 2^(2x)) \
p^+ >= log_2((n_i+1)! dot ln(2)^(1-n_i) dot h_i^(-(n_i+1)) dot 2^(- 2x_i - n_i)) \
p^+ >= log_2((n_i+1)!) + (1-n_i)log_2(ln(2)) - (n_i+1)log_2(h_i) + log_2(2^(- 2x_i - n_i)) \
p^+ >= log_2((n_i+1)!) + (n_i+1)(log_2(h_i^(-1)) - log_2(ln(2)) - 1) - 2x_i + 2log_2(ln(2))\
$

\

$
2^(-p^-) <= 1/(n_i+1)! ln(2)^(n_i-1) h_i^(n_i+1) 2^(2x_i + n_i) 1/(1 - 2^(x_i)) \
p^- >= log_2((n_i+1)! dot ln(2)^(1-n_i) dot h_i^(-(n_i+1)) dot 2^(- 2x_i - n_i) dot (1 - 2^(x_i))) \
p^- >= log_2((n_i+1)!) + (1-n_i)log_2(ln(2)) - (n_i+1)log_2(h_i) + log_2(2^(- 2x_i - n_i)) + log_2(1 - 2^(x_i)) \
p^- >= log_2((n_i+1)!) + (n_i+1)(log_2(h_i^(-1)) - log_2(ln(2)) - 1) - 2x_i + log_2(1 - 2^(x_i)) + 2log_2(ln(2))\
$
]

Finally, we arrive at a relationship between the precision 
of the format, the degree $n_i$ of the polynomial, 
the size of the interval, $h_i$, and, given by the last term, the curvature of the
function in that same interval.

$
p^+ ~ Omega(log_2((n_i + 1) !) + (n_i + 1) log_2(h_i^(-1)) - 2x_i) \
$

$
p^- ~ Omega(log_2((n_i + 1) !) + (n_i + 1) log_2(h_i^(-1)) - 2x_i + log_2(1 - 2^(x_i))) \
$

#pagebreak()

=== LNS-Float & Float-LNS Convertion Functions Aproximations

#math.equation(numbering: none, block: true)[
$
"float2lns"(x) := log_2(1 + x) &= 1/ln(2) sum_(n >= 1) (-1)^n / n x^n, |x| < 1 \
dif^k/(dif x^k) log_2(1 + x) &= 1/ln(2) dif^k/(dif x^k) sum_(n >= 1) (-1)^n / n x^n \
\
dif^k/(dif x^k) log_2(1 + x) &= 1/ln(2) sum_(n >= 1) (-1)^n / n n!/(n - k)! x^(n - k) \
\
lr(|(-1)^(n+1) / (n + 1) (n + 1)!/(n + 1 - k)! x^(n + 1 - k)|) &< lr(|(-1)^n / n n!/(n - k)! x^(n - k)|) \
1 / (n + 1) (n + 1)!/(n + 1 - k)! x^(n + 1 - k) &< 1 / n n!/(n - k)! x^(n + 1 - k) \
n x &< (n + 1 - k) \
x &< (n + 1 - k) / n \
x &< 1 - (k - 1) / n \
n &> (k - 1)/(1 - x) \
$
]

#math.equation(numbering: none, block: true)[
$
lr(|dif^k/(dif x^k) log_2(1 + x)|) &<=
lr(|1/ln(2) sum_(n = 1)^(n = i) (-1)^n / n n!/(n - k)! x^(n - k)|) +
lr(|1/ln(2) (-1)^(i + 1) / (i + 1) x^(i + 1)|), i = ceil((k - 1)/(1 - x)) \
$
]

By the Alternating Series Test.

#math.equation(numbering: none, block: true)[
$
epsilon_i &<= 1/(n_i+1)! 1/ln(2) 1/(n_i + 2) x^(n_i + 1) h_i^(n_i + 1)
$
]

#math.equation(numbering: none, block: true)[
$
p &>= Omega(log_2((n_i + 1)!) + (n_i + 1)(log_2(h_i^(-1)) - log_2(x_i)) - x_i) \
$
]

#math.equation(numbering: none, block: true)[
$
"lns2float"(x) &:= 2^x - 1, |x| < 1\
\
lr(|dif^k/(dif x^k)(2^x - 1)|) &= ln(2)^k 2^x \
\
epsilon_i &<= 1/(n_i + 1)! ln(2)^(n_i + 1) 2^(x_i) h_i^(n_i + 1)
$
]

#math.equation(numbering: none, block: true)[
$
p &>= Omega(log_2((n_i + 1)!) + (n_i + 1)(log_2(h_i^(-1)) - log_2(ln(2))) - x_i) \
$
]

#pagebreak()

== Newton's Divided Differences

=== Method

Newton's divided differences construct an interpolating polynomial of degree $n$ through $n+1$
sample points ${(x_i, f_i) | 0 <= i <= n}$. The polynomial is expressed in Newton form:

$
P(x) = sum_(i=0)^n [y_0, dots, y_i] product_(j=0)^(i-1) (x - x_j)
$

where $[y_0, ..., y_k]$ denotes the $k$-th order divided difference, computed recursively as:

$
[y_i] &= f(x_i) \
[y_i, ..., y_(i+k)] &= ([y_(i+1), ..., y_(i+k)] - [y_i, ..., y_(i+k-1)]) / (x_(i+k) - x_i)
$

Evaluation via Horner's method requires $n$ multiplications and $n$ additions for a degree-$n$ polynomial, which is optimal.


=== Application to LNS

For $f^+$ and $f^-$, sample points can be placed non-uniformly, with higher density near $x = 0$
where the functions curve sharply, and sparser sampling in the flat tail near $-infinity$.
This is the key advantage over uniform splines: the same number of points can cover a much wider domain with controlled error.

For a piecewise approach, the domain is split into segments and a separate low-degree Newton polynomial is fitted to each.
Segment boundaries are chosen adaptively based on the local curvature.

=== Memory and Evaluation Cost

Storing $n+1$ points requires $2(n+1)$ values: the $x_i$ ones and the divided difference coefficients.
For a degree-$d$ polynomial on $k$ segments, the total storage is $O(k dot d)$ values. Evaluation requires $d$ multiply-adds per query.

=== Considerations

Newton's divided differences are numerically stable when using Horner's scheme,
but the divided differences themselves can suffer from cancellation when computed in floating point for closely spaced points.
For fixed-point arithmetic, careful scaling of the coefficients is needed to avoid overflow during evaluation.

/*
== Minimax Polynomial Approximation (Remez Algorithm)

=== Method

Rather than interpolating through sample points, minimax approximation finds the polynomial of degree $n$ that minimises the maximum absolute error over the entire domain $[a, b]$:

$
p^*(x) = arg min_(p in cal(P)_n) max_(x in [a,b]) |f(x) - p(x)|
$

By the equioscillation theorem (Chebyshev), the optimal polynomial achieves its maximum error at exactly $n+2$ alternating points. The Remez algorithm iteratively refines a candidate set of equioscillation points until convergence.

=== Application to LNS

For $f^+$, the domain is bounded $(-infinity, 0]$ and the function is smooth, so a single polynomial of moderate degree (typically 4–8) can achieve very small error over a truncated domain $[x_{\min}, 0]$. The tail below $x_{\min}$ is handled by clamping since $f^+(x) approx 0$ for sufficiently negative $x$.

For $f^-$, the singularity at $x = 0$ prevents a single polynomial from covering the full domain. A piecewise approach is needed, or a change of variable such as $t = -x$ combined with approximating $f^-(−t)$ near $t = 0$ separately.

=== Memory and Evaluation Cost

A single degree-$n$ minimax polynomial requires storing $n+1$ coefficients. For lns16, a degree-6 polynomial fits in $7 times 2 = 14$ bytes per function, compared to the 72–252 bytes required by spline tables. Evaluation via Horner's method costs $n$ multiply-adds.

=== Considerations

Minimax approximation gives the theoretically optimal worst-case error for a given polynomial degree. The Remez algorithm is well established and its output is a set of fixed coefficients that can be computed offline and hardcoded. The main challenge for hardware is that the coefficients are real-valued and must be quantised to fixed point without degrading the approximation quality.

== Piecewise Chebyshev Approximation

=== Method

Chebyshev approximation fits a truncated Chebyshev series to $f$ on each subinterval $[a_k, b_k]$. The Chebyshev polynomials $T_n(x)$ form an orthogonal basis on $[-1, 1]$ and minimise the maximum norm among monic polynomials of degree $n$, making them near-optimal in the minimax sense.

For an interval $[a, b]$, the change of variable $t = (2x - a - b)/(b - a)$ maps to $[-1, 1]$, and the approximation is:

$
f(x) approx sum_(k=0)^(n) c_k T_k(t), quad c_k = 2/n sum_(j=1)^(n) f(x_j) T_k(t_j)
$

where $x_j$ are the Chebyshev nodes. Truncating after $n+1$ terms gives a near-minimax approximation.

=== Application to LNS

Piecewise Chebyshev is particularly suited to the subtraction function, where the singularity at $x = 0$ can be handled by assigning a dedicated segment $[x_{-1}, 0)$ with a higher-degree polynomial, while the smooth tail is covered by low-degree segments with wider spacing.

The coefficients of each segment can be quantised to fixed point and stored in a compact table. Unlike Newton's divided differences, Chebyshev coefficients have bounded growth and are less sensitive to quantisation.

=== Memory and Evaluation Cost

For $k$ segments of degree $d$, storage is $k(d+2)$ values (coefficients plus boundary). Evaluation requires $d$ multiply-adds per query using Clenshaw's recurrence, which is numerically stable and equivalent in cost to Horner's method.

== Comparison of Methods

#figure(
  table(
    columns: 5,
    align: (left, center, center, center, left),
    [Method], [Memory], [Eval cost], [Handles singularity], [Notes],
    [Linear spline (XF)],  [High], [4 ops], [Partial], [Simple, synthesisable in 2 cycles],
    [Linear spline (XMB)], [High], [1 MAC], [Partial], [Single cycle, used in hardware],
    [Newton NDD],          [Low],  [$d$ MACs], [With piecewise], [Non-uniform point placement],
    [Minimax (Remez)],     [Very low], [$d$ MACs], [With piecewise], [Optimal worst-case error],
    [Piecewise Chebyshev], [Low], [$d$ MACs], [Yes], [Near-minimax, stable coefficients],
  ),
  caption: [Qualitative comparison of approximation methods. $d$ is polynomial degree per segment.],
) <tab:method_comparison>

= Extended Formats: lns32 and lns64

== Motivation

For lns32 Q16.15, the argument to the correction functions $x = L_y - L_x$ ranges over 31 bits (excluding the sign). At the error level required for one-bit precision in Q16.15, a linear spline covering this domain would require tens of thousands of rows — far beyond any practical hardware budget.

For lns64 Q32.31, the situation is worse by a further factor of $2^{16}$.

The transition to compact polynomial approximations is therefore not optional for lns32 and lns64 — it is required.

== Domain Analysis

For lns32, the full domain of $f^+$ is $(-2^{15}, 0]$ in fixed-point units (Q16.15). However, for $x < -52$ the value $2^x < 2^{-52}$, which is below the precision of 64-bit floating point. In practice, the correction function saturates to 0 for sufficiently negative $x$, and the effective domain requiring approximation is much narrower.

The effective domain can be defined as the range of $x$ where $f^+(x) > 2^{-F}$, i.e., where the correction is larger than the LSB of the format. For lns32 Q16.15 with $F = 15$:

$
f^+(x) > 2^{-15} => log_2(1 + 2^x) > 2^{-15} => 2^x > 2^{2^{-15}} - 1 approx 2^{-15} dot ln(2)
$

giving an effective lower bound around $x approx -52$. Beyond this point the correction can be set to zero without loss of precision. The effective domain is therefore approximately $[-52, 0]$ regardless of the total exponent width, which makes compact polynomial approximation feasible even for lns32 and lns64.

The subtraction function $f^-$ has a narrower effective domain: for $x < -52$, $f^-(x) approx f^+(x)$ and both can be clamped. The critical region is near $x = 0$ where the singularity dominates.

== Implications for Approximation

The observation that the effective domain is $O(52)$ in natural units (independent of format width) means that the same polynomial approximation can in principle be reused across lns8, lns16, lns32, and lns64 with only coefficient rescaling to account for the different fixed-point representations. This is a significant simplification and suggests a unified approximation strategy:

+ Compute the minimax or Chebyshev approximation for $f^+$ and $f^-$ in real-valued arithmetic on $[-52, 0]$.
+ Quantise coefficients to the fixed-point precision of the target format.
+ Evaluate using Horner's method with integer arithmetic.

= Evaluation Framework

== Error Metrics

Approximation quality is measured by comparing the output of the approximation against the true value of $f^+(x)$ or $f^-(x)$ computed in 64-bit floating point. The following metrics are tracked:

- *Maximum absolute error (MAE)*: $max |f(x) - hat(f)(x)|$ in fixed-point units.
- *Maximum relative error (MRE)*: $max |f(x) - hat(f)(x)| / |f(x)|$.
- *Average absolute error*: $E[|f(x) - hat(f)(x)|]$.
- *Error in bits*: $log_2("MAE") - log_2(2^{-F}) = log_2("MAE" dot 2^F)$, where $F$ is the number of fractional bits.

An error of $<= 1$ bit means the approximation is off by at most one LSB of the format.

== Test Input Distribution

Random inputs are sampled by drawing a uniformly random exponent from the format's representable range and converting to float via $2^e$. To avoid overflow in addition tests, the exponent is capped:

#figure(
  table(
    columns: 4,
    align: center,
    [Format], [Exponent cap], [Value range], [Worst-case add],
    [lns8  Q4.3],  [$[-3, +3]$],  [$[0.125, 8.0]$],       [$16.0 = 2^4$],
    [lns16 Q8.7],  [$[-6, +6]$],  [$[0.015625, 64.0]$],   [$128.0 = 2^7$],
    [lns32 Q16.15],[$[-6, +6]$],  [$[0.015625, 64.0]$],   [$128.0 = 2^7$],
    [lns64 Q32.31],[$[-6, +6]$],  [$[0.015625, 64.0]$],   [$128.0 = 2^7$],
  ),
  caption: [Test input ranges and exponent caps by format],
) <tab:test_ranges>

The same cap is applied to bfloat16 in comparisons to ensure a fair benchmark. Without capping, both lns and floating-point formats exhibit large errors because their fractional bits are consumed by representing the integer part of large values, leaving no precision for sub-unit differences.

== Benchmark Operations

For each format and approximation method, five operations are tested:

- *rt*: Round-trip conversion (float $->$ LNS $->$ float). Measures quantization error only.
- *mul*: Multiplication. Exact in LNS; tests exponent addition only.
- *div*: Division. Exact in LNS; tests exponent subtraction only.
- *add*: Addition. Exercises $f^+$ approximation.
- *sub*: Subtraction. Exercises $f^-$ approximation, including near-cancellation cases.

Results are reported as min/avg/max absolute and relative error, and compared against bfloat16 as a 16-bit floating-point baseline for lns16.

= Open Questions and Future Work

== Approximation Method Selection

The primary open question is which approximation method provides the best trade-off between accuracy, memory, and hardware evaluation cost for each format. The following investigations are planned:

- Implement Newton's divided differences with adaptive point placement for lns8 and lns16 and compare against the existing XMB spline tables at the same memory budget.
- Apply the Remez algorithm to compute minimax polynomials of degree 4–8 for $f^+$ and $f^-$ on the effective domain $[-52, 0]$, quantise to fixed point, and measure the resulting error.
- Implement piecewise Chebyshev approximation with special handling of the $f^-$ singularity and evaluate on all four formats.

== Fixed-Point Coefficient Quantisation

All polynomial methods require offline computation of coefficients in real arithmetic followed by quantisation to the target fixed-point format. The interaction between polynomial degree, coefficient wordlength, and approximation error under fixed-point evaluation is non-trivial and requires careful analysis, particularly for lns32 and lns64 where intermediate products in Horner evaluation may require extended-precision accumulators.

== Hardware Implementation for lns32 and lns64

The LNSU design from previous work was optimised for lns16 with XMB splines and single-cycle latency. A polynomial evaluator for lns32 or lns64 will have a different area and latency profile. The degree of the polynomial and the wordlength of the coefficients will determine the number of DSP blocks required. An initial estimate suggests that a degree-6 evaluator in Q16.15 arithmetic would require 3–4 DSPs and would be pipelinable to maintain high throughput.

== Conversion Operations

As noted in previous work, conversion between LNS and integer/float formats has not yet been implemented. For practical use of lns32 and lns64 in software simulation and hardware, these conversions are necessary. The conversion from float to LNS requires computing $log_2(|x|)$ in fixed point, which can itself be approximated by a polynomial in the mantissa after extracting the IEEE-754 exponent.

== Format Generalisation

The current library supports lns8, lns16 as templates parameterised by $\langle N, I, F \rangle$. Extending this to lns32 and lns64 requires ensuring that intermediate arithmetic (exponent differences, polynomial evaluation) does not overflow the available integer types. For lns64, the exponent field is 63 bits wide, requiring 128-bit intermediate arithmetic in software simulation.

#bibliography("bibliography.bib", style: "chicago-author-date")
*/

